name: My Fisrt Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
        - name: Welcome message
          run: echo "My first Github Actions Job"
        
        - name: Checkout Repo
          uses: actions/checkout@v4
          with:
            repository: ''  
        
        - name: List files
          run: ls -la
        
        - name: Present working Directory
          run: pwd
        
        - name: Read File
          run: cat README.md