name: Generate ASCII Artwork

on: push

jobs:
   ascii_job: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Install Cowsays
      run: sudo apt-get install cowsay
    
    - name: Execute Cowsay CMD
      run: cowsay -f dragon "Run for Cover, I am a Dragon....RAWR"  dragon.txt
   
 
    - name: Read file
      run: cat dragon.txt
    
    - name: Checkout Repo files
      run: ls -ltra