name: Matrix-config-wf

on: push

jobs:
    docker:
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      steps:
      - name: Docker Build
        run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
      
      - name: Docker Login
        run: echo docker login --username=$${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
    deploy:
        strategy:
           matrix:
            os: [ubuntu-latest, ubuntu-20.04, windows-latest]
            images: [hello-world, alpine]
            exclude:
              - images: alpine
                os: windows-latest
        runs-on: ${{ matrix.os }}
        steps:
        - name: Echo Docker Details
          run: docker info

        - name: Run image on ${{ matrix.os }}
          run: docker run ${{ matrix.images }}

    